<div class="mobile-search-area d-xl-none mb-15px">
    <div class="container">
        <div class="row">
            <div class="col-md-12">
                <div class="search-element media-body">
                    <form class="d-flex" action="#">
                        <div class="search-category">
                            <select>
                                <option value="0">All categories</option>
                                <option value="12">Laptop</option>
                                <option value="13">- - Hot Categories</option>
                                <option value="19">- - - - Dresses</option>
                                <option value="20">- - - - Jackets &amp; Coats</option>
                                <option value="21">- - - - Sweaters</option>
                                <option value="22">- - - - Jeans</option>
                                <option value="23">- - - - Blouses &amp; Shirts</option>
                                <option value="14">- - Outerwear &amp; Jackets</option>
                                <option value="24">- - - - Basic Jackets</option>
                                <option value="25">- - - - Real Fur</option>
                                <option value="26">- - - - Down Coats</option>
                                <option value="27">- - - - Blazers</option>
                                <option value="28">- - - - Trench Coats</option>
                                <option value="15">- - Weddings &amp; Events</option>
                                <option value="29">- - - - Wedding Dresses</option>
                                <option value="30">- - - - Evening Dresses</option>
                                <option value="31">- - - - Prom Dresses</option>
                                <option value="32">- - - - Bridesmaid Dresses</option>
                                <option value="33">- - - - Wedding Accessories</option>
                                <option value="16">- - Bottoms</option>
                                <option value="34">- - - - Skirts</option>
                                <option value="35">- - - - Leggings</option>
                                <option value="36">- - - - Pants &amp; Capris</option>
                                <option value="37">- - - - Wide Leg Pants</option>
                                <option value="38">- - - - Shorts</option>
                                <option value="17">- - Tops &amp; Sets</option>
                                <option value="39">- - - - Tank Tops</option>
                                <option value="40">- - - - Suits &amp; Sets</option>
                                <option value="41">- - - - Jumpsuits</option>
                                <option value="42">- - - - Rompers</option>
                                <option value="43">- - - - Sleep &amp; Lounge</option>
                                <option value="18">- - Accessories</option>
                                <option value="44">- - - - Eyewear &amp; Accessories</option>
                                <option value="45">- - - - Hats &amp; Caps</option>
                                <option value="46">- - - - Belts &amp; Cummerbunds</option>
                                <option value="47">- - - - Scarves &amp; Wraps</option>
                                <option value="48">- - - - Gloves &amp; Mittens</option>
                                <option value="49">Computer</option>
                                <option value="50">- - Bottoms</option>
                                <option value="53">- - - - Skirts</option>
                                <option value="54">- - - - Leggings</option>
                                <option value="55">- - - - Jeans</option>
                                <option value="56">- - - - Pants &amp; Capris</option>
                                <option value="57">- - - - Shorts</option>
                                <option value="51">- - Outerwear &amp; Jackets</option>
                                <option value="58">- - - - Trench</option>
                                <option value="59">- - - - Genuine Leather</option>
                                <option value="60">- - - - Parkas</option>
                                <option value="61">- - - - Down Jackets</option>
                                <option value="62">- - - - Wool &amp; Blends</option>
                                <option value="52">- - Underwear &amp; Loungewear</option>
                                <option value="63">- - - - Boxers</option>
                                <option value="64">- - - - Briefs</option>
                                <option value="65">- - - - Long Johns</option>
                                <option value="66">- - - - Men's Sleep &amp; Lounge</option>
                                <option value="67">- - - - Pajama Sets</option>
                                <option value="68">Smartphone</option>
                                <option value="69">- - Accessories &amp; Parts</option>
                                <option value="75">- - - - Cables &amp; Adapters</option>
                                <option value="76">- - - - Batteries</option>
                                <option value="77">- - - - Chargers</option>
                                <option value="78">- - - - Bags &amp; Cases</option>
                                <option value="79">- - - - Electronic Cigarettes</option>
                                <option value="70">- - Audio &amp; Video</option>
                                <option value="80">- - - - Televisions</option>
                                <option value="81">- - - - TV Receivers</option>
                                <option value="82">- - - - Projectors</option>
                                <option value="83">- - - - Audio Amplifier Boards</option>
                                <option value="84">- - - - TV Sticks</option>
                                <option value="71">- - Camera &amp; Photo</option>
                                <option value="85">- - - - Digital Cameras</option>
                                <option value="86">- - - - Camcorders</option>
                                <option value="87">- - - - Camera Drones</option>
                                <option value="88">- - - - Action Cameras</option>
                                <option value="89">- - - - Photo Studio Supplies</option>
                                <option value="72">- - Portable Audio &amp; Video</option>
                                <option value="90">- - - - Headphones</option>
                                <option value="91">- - - - Speakers</option>
                                <option value="92">- - - - MP3 Players</option>
                                <option value="93">- - - - VR/AR Devices</option>
                                <option value="94">- - - - Microphones</option>
                                <option value="73">- - Smart Electronics</option>
                                <option value="95">- - - - Wearable Devices</option>
                                <option value="96">- - - - Smart Home Appliances</option>
                                <option value="97">- - - - Smart Remote Controls</option>
                                <option value="98">- - - - Smart Watches</option>
                                <option value="99">- - - - Smart Wristbands</option>
                                <option value="74">- - Video Games</option>
                                <option value="100">- - - - Handheld Game Players</option>
                                <option value="101">- - - - Game Controllers</option>
                                <option value="102">- - - - Joysticks</option>
                                <option value="103">- - - - Stickers</option>
                                <option value="104">Game Consoles</option>
                                <option value="105">Mp3 &amp; headphone</option>
                                <option value="106">Tv &amp; Video</option>
                                <option value="107">Watches</option>
                                <option value="108">Washing Machine</option>
                                <option value="109">Camera</option>
                                <option value="110">Audio &amp; Theater</option>
                                <option value="111">Accessories</option>
                                <option value="112">Games &amp; Consoles</option>
                            </select>
                        </div>
                        <input type="text" placeholder="Enter your search key ... " />
                        <button><i class="icon-magnifier"></i></button>
                    </form>
                </div>
            </div>
        </div>
    </div>
</div>